dist: trusty
sudo: false

language: node_js
cache: npm

addons:
  apt:
    packages:
      - libxml2-utils

node_js: v10
env:
- npm_version=6
  DEBUG=tape-spawn
  SHARP_IGNORE_GLOBAL_LIBVIPS=1

# before_install:
# - npm i -g npm@${npm_version}
before_install:
- npm config --global set prefer-offline true

install:
- npm ci
- npm run install:all

script:
- ./bin/cli.js --help
- npm test
- make build-odt
- xmllint --noout dist/book.fodt 2>&1

before_deploy:
- git-lfs pull
- make build-html
- make build-docbook

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GH_TOKEN"
    local-dir: dist
    on:
      branch: master
  - provider: releases
    prerelease: true
    skip-cleanup: true
    api-key: "$GH_TOKEN"
    file-glob: true
    file: dist/book.*
    on:
      tags: true
  - provider: npm
    skip-cleanup: true
    on:
      tags: true
    email: "hi@oncletom.io"
    api-key: "$NPM_TOKEN"
